version: 2

project_name: manuscript-cli

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      manuscript-core-{{.Os }}-{{.Arch}}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "manuscript-core-checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
