name: "🕷️ Bug report"
description: Report errors or unexpected behavior
labels:
  - bug
body:
  - type: checkboxes
    attributes:
      label: Self Checks
      description: "To make sure we get to you in time, please check the following :"
      options:
        - label: This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
          required: true
        - label: I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
          required: true
        - label: I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.
          required: true

  - type: textarea
    attributes:
      label: Environment
      description: Tell us about your environment
      placeholder: >
        $ manuscript-gui version 
          manuscript-cli version 1.1.0

        $ manuscript-cli version --verbose
        Manuscript CLI:
          Version:    1.0.4
          Go version: go1.21.0
          OS/Arch:    darwin/arm64

        System Information:
          Darwin MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: x86_64

        Docker Environment:
          Docker Engine:   '24.0.6'
          Docker Desktop:  '24.0.6'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including screenshots and a bug report log. Please use the right markdown syntax for code blocks.
      placeholder: Having detailed steps helps us reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false