blank_issues_enabled: false
contact_links:
  - name: "\U0001F4E7 Discussions"
    url: https://github.com/chainbase-labs/manuscript-core/discussions
    about: To ask a question or request support for using Manuscript