version: '3.2'
name: get_token_metas_to_postgres
services:
  jobmanager:
    image: ${MS_FLINK_IMAGE:-ms_flink}
    user: "flink"
    command: "standalone-job --job-classname com.chainbase.manuscript.ETLProcessor /opt/flink/manuscript.yaml --fromSavepoint /opt/flink/savepoint"
    volumes:
      - ${MANUSCRIPT_DATA_PATH:-./data}/statuspoint/checkpoint:/opt/flink/checkpoint
      - ${MANUSCRIPT_DATA_PATH:-./data}/statuspoint/savepoint:/opt/flink/savepoint
      - ${MANUSCRIPT_DATA_PATH:-./data}/log:/opt/flink/log
      - ${MANUSCRIPT_DATA_PATH:-./data}/slink_files:/opt/flink/sink_file_path
      - ${MANUSCRIPT_PATH:-./manuscript.yaml}:/opt/flink/manuscript.yaml
    networks:
      - ms_network

  taskmanager:
    image: ${MS_FLINK_IMAGE:-ms_flink}
    user: "flink"
    depends_on:
      - jobmanager
    command: "taskmanager"
    scale: 1
    volumes:
      - ${MANUSCRIPT_DATA_PATH:-./data}/statuspoint/checkpoint:/opt/flink/checkpoint
      - ${MANUSCRIPT_DATA_PATH:-./data}/statuspoint/savepoint:/opt/flink/savepoint
      - ${MANUSCRIPT_DATA_PATH:-./data}/log:/opt/flink/log
      - ${MANUSCRIPT_DATA_PATH:-./data}/sink_files:/opt/flink/sink_file_path
      - ${MANUSCRIPT_PATH:-./manuscript.yaml}:/opt/flink/manuscript.yaml
    networks:
      - ms_network

  postgres:
    image: postgres:16.4
    volumes:
      - ${MANUSCRIPT_DATA_PATH:-./data}/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-public}
    networks:
      - ms_network
    restart: unless-stopped

networks:
  ms_network: