FROM repository.chainbase.com/network/flink:v1.18-0.2
# Use the official Flink image as base for the final image

# Copy the built JAR from the build stage
ADD runner/target/runner-1.0-SNAPSHOT.jar /opt/flink/lib/runner-1.0-SNAPSHOT.jar